name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.DOCKER_USERNAME }}/nextcloud

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nextcloud:${{ github.event.inputs.tag }} .

      - name: Push the Docker image
        run: docker push -t ${{ secrets.DOCKER_USERNAME }}/nextcloud:${{ github.event.inputs.tag }}
